spring.application.name=travel-explore-backend
management.endpoints.web.exposure.include=health,info,mappings

# MongoDB
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/Travel_Explore}
